spring:
  application:
    name: notification-service
  datasource:
    url: jdbc:mysql://localhost:3306/notification-db
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

server:
  port: 8006
