spring:
  application:
    name: notification-service
  datasource:
    url: jdbc:mysql://localhost:3306/notificationdb
    username: root
    password: SQL_123basmala
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  rabbitmq:
    password: secret
    username: myuser


server:
  port: 8006
  servlet:
    context-path: /notification-api

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
